version: "3.9"

services:
  app:
    platform: linux/amd64
    image: yuu-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - "127.0.0.1:4000:3000"
